Highcharts.chart('tree_chart_1', {
  series: [
    {
      type: "treemap",
      layoutAlgorithm: 'squarified',
      allowDrillToNode: true,
      levelIsConstant: false,
      alternateStartingDirection: true,
      levels: [
        {
          level: 1,
          layoutAlgorithm: 'squarified',
          dataLabels: {
            enabled: true,
            align: 'left',
            verticalAlign: 'top'
          }
        }
      ],
      data: [
        {
          name: 'Städtische Galerie im Lenbachhaus',
          id: 'A',
          color: '#969597'
        }, {
          name: 'Schackgalerie',
          id: 'B',
          color: '#D5AEB7'
        }, {
          name: 'Pinakothek der Moderne',
          id: 'C',
          color: '#CCCED7'
        }, {
          name: 'Neue Pinakothek',
          id: 'D',
          color: '#C7D0AE'
        }, {
          name: 'Museum Mensch und Natur',
          id: 'E',
          color: '#A5C2D4'
        }, {
          name: 'Museum Brandhorst',
          id: 'F',
          color: '#D9CFB3'
        }, {
          name: 'Münchner Stadtmuseum',
          id: 'G',
          color: '#AECCC4'
        }, {
          name: 'Deutsches Museum - Verkehrszentrum',
          id: 'H',
          colorValue: 8,
          color: '#D2BCA9'
        }, {
          name: 'Deutsches Museum - Museumsinsel',
          id: 'I',
          color: '#CB9D88'
        }, {
          name: 'Bayerisches Nationalmuseum',
          id: 'J',
          color: '#8D9C88'
        }, {
          name: 'Alte Pinakothek',
          id: 'K',
          color: '#DEEDEE'
        }, {
          name: 'Jan',
          parent: 'A',
          value: 24491
        }, {
          name: 'Feb',
          parent: 'A',
          value: 26003
        }, {
          name: 'Mar',
          parent: 'A',
          value: 8844
        }, {
          name: 'Apr',
          parent: 'A',
          value: 7000
        }, {
          name: 'May',
          parent: 'A',
          value: 5234
        }, {
          name: 'Jun',
          parent: 'A',
          value: 5544
        }, {
          name: 'Jul',
          parent: 'A',
          value: 4545
        }, {
          name: 'Aug',
          parent: 'A',
          value: 0
        }, {
          name: 'Sep',
          parent: 'A',
          value: 0
        }, {
          name: 'Oct',
          parent: 'A',
          value: 0
        }, {
          name: 'Nov',
          parent: 'A',
          value: 3809
        }, {
          name: 'Dec',
          parent: 'A',
          value: 3282
        }, {
          name: 'Jan',
          parent: 'B',
          value: 878
        }, {
          name: 'Feb',
          parent: 'B',
          value: 759
        }, {
          name: 'Mar',
          parent: 'B',
          value: 815
        }, {
          name: 'Apr',
          parent: 'B',
          value: 721
        }, {
          name: 'May',
          parent: 'B',
          value: 469
        }, {
          name: 'Jun',
          parent: 'B',
          value: 548
        }, {
          name: 'Jul',
          parent: 'B',
          value: 674
        }, {
          name: 'Aug',
          parent: 'B',
          value: 572
        }, {
          name: 'Sep',
          parent: 'B',
          value: 764
        }, {
          name: 'Oct',
          parent: 'B',
          value: 1501
        }, {
          name: 'Nov',
          parent: 'B',
          value: 835
        }, {
          name: 'Dec',
          parent: 'B',
          value: 652
        }, {
          name: 'Jan',
          parent: 'C',
          value: 32829
        }, {
          name: 'Feb',
          parent: 'C',
          value: 26183
        }, {
          name: 'Mar',
          parent: 'C',
          value: 33216
        }, {
          name: 'Apr ',
          parent: 'C',
          value: 70569
        }, {
          name: 'May',
          parent: 'C',
          value: 48231
        }, {
          name: 'Jun',
          parent: 'C',
          value: 45160
        }, {
          name: 'Jul',
          parent: 'C',
          value: 49904
        }, {
          name: 'Aug',
          parent: 'C',
          value: 24299
        }, {
          name: 'Sep',
          parent: 'C',
          value: 24627
        }, {
          name: 'Oct',
          parent: 'C',
          value: 28496
        }, {
          name: 'Nov',
          parent: 'C',
          value: 25761
        }, {
          name: 'Dec',
          parent: 'C',
          value: 28098
        }, {
          name: 'Jan',
          parent: 'D',
          value: 22422
        }, {
          name: 'Feb',
          parent: 'D',
          value: 29640
        }, {
          name: 'Mar',
          parent: 'D',
          value: 28642
        }, {
          name: 'Apr',
          parent: 'D',
          value: 30330
        }, {
          name: 'May',
          parent: 'D',
          value: 17603
        }, {
          name: 'Jun',
          parent: 'D',
          value: 16598
        }, {
          name: 'Jul',
          parent: 'D',
          value: 24254
        }, {
          name: 'Aug',
          parent: 'D',
          value: 22685
        }, {
          name: 'Sep',
          parent: 'D',
          value: 17876
        }, {
          name: 'Oct',
          parent: 'D',
          value: 23743
        }, {
          name: 'Nov',
          parent: 'D',
          value: 18794
        }, {
          name: 'Dec',
          parent: 'D',
          value: 20289
        }, {
          name: 'Jan',
          parent: 'E',
          value: 18211
        }, {
          name: 'Feb',
          parent: 'E',
          value: 14486
        }, {
          name: 'Mar',
          parent: 'E',
          value: 12783
        }, {
          name: 'Apr',
          parent: 'E',
          value: 23250
        }, {
          name: 'May',
          parent: 'E',
          value: 11670
        }, {
          name: 'Jun',
          parent: 'E',
          value: 13650
        }, {
          name: 'Jul',
          parent: 'E',
          value: 16513
        }, {
          name: 'Aug',
          parent: 'E',
          value: 10742
        }, {
          name: 'Sep',
          parent: 'E',
          value: 11199
        }, {
          name: 'Oct',
          parent: 'E',
          value: 14906
        }, {
          name: 'Nov',
          parent: 'E',
          value: 11755
        }, {
          name: 'Dec',
          parent: 'E',
          value: 13791
        }, {
          name: 'Jan',
          parent: 'F',
          value: 14552
        }, {
          name: 'Feb',
          parent: 'F',
          value: 12020
        }, {
          name: 'Mar',
          parent: 'F',
          value: 11895
        }, {
          name: 'Apr',
          parent: 'F',
          value: 17876
        }, {
          name: 'May',
          parent: 'F',
          value: 13351
        }, {
          name: 'Jun',
          parent: 'F',
          value: 11070
        }, {
          name: 'Jul',
          parent: 'F',
          value: 15545
        }, {
          name: 'Aug',
          parent: 'F',
          value: 11671
        }, {
          name: 'Sep',
          parent: 'F',
          value: 11672
        }, {
          name: 'Oct',
          parent: 'F',
          value: 17838
        }, {
          name: 'Nov',
          parent: 'F',
          value: 13881
        }, {
          name: 'Dec',
          parent: 'F',
          value: 12875
        }, {
          name: 'Jan',
          parent: 'G',
          value: 10316
        }, {
          name: 'Feb',
          parent: 'G',
          value: 11868
        }, {
          name: 'Mar',
          parent: 'G',
          value: 16252
        }, {
          name: 'Apr',
          parent: 'G',
          value: 11316
        }, {
          name: 'May',
          parent: 'G',
          value: 8827
        }, {
          name: 'Jun',
          parent: 'G',
          value: 8471
        }, {
          name: 'Jul',
          parent: 'G',
          value: 10732
        }, {
          name: 'Aug',
          parent: 'G',
          value: 5733
        }, {
          name: 'Sep',
          parent: 'G',
          value: 7806
        }, {
          name: 'Oct',
          parent: 'G',
          value: 11365
        }, {
          name: 'Nov',
          parent: 'G',
          value: 13884
        }, {
          name: 'Dec',
          parent: 'G',
          value: 10778
        }, {
          name: 'Jan',
          parent: 'H',
          value: 10837
        }, {
          name: 'Feb',
          parent: 'H',
          value: 8725
        }, {
          name: 'Mar',
          parent: 'H',
          value: 6328
        }, {
          name: 'Apr',
          parent: 'H',
          value: 11882
        }, {
          name: 'May',
          parent: 'H',
          value: 6651
        }, {
          name: 'Jun',
          parent: 'H',
          value: 7704
        }, {
          name: 'Jul',
          parent: 'H',
          value: 9775
        }, {
          name: 'Aug',
          parent: 'H',
          value: 8257
        }, {
          name: 'Sep',
          parent: 'H',
          value: 6616
        }, {
          name: 'Oct',
          parent: 'H',
          value: 8607
        }, {
          name: 'Nov',
          parent: 'H',
          value: 6857
        }, {
          name: 'Dec',
          parent: 'H',
          value: 8230
        }, {
          name: 'Jan',
          parent: 'I',
          value: 74203
        }, {
          name: 'Feb',
          parent: 'I',
          value: 64569
        }, {
          name: 'Mar',
          parent: 'I',
          value: 70486
        }, {
          name: 'Apr',
          parent: 'I',
          value: 115341
        }, {
          name: 'May',
          parent: 'I',
          value: 66398
        }, {
          name: 'Jun',
          parent: 'I',
          value: 78247
        }, {
          name: 'Jul',
          parent: 'I',
          value: 109202
        }, {
          name: 'Aug',
          parent: 'I',
          value: 103140
        }, {
          name: 'Sep',
          parent: 'I',
          value: 66637
        }, {
          name: 'Oct',
          parent: 'I',
          value: 90747
        }, {
          name: 'Nov',
          parent: 'I',
          value: 59571
        }, {
          name: 'Dec',
          parent: 'I',
          value: 67154
        }, {
          name: 'Jan',
          parent: 'J',
          value: 7053
        }, {
          name: 'Feb',
          parent: 'J',
          value: 5555
        }, {
          name: 'Mar',
          parent: 'J',
          value: 5537
        }, {
          name: 'Apr',
          parent: 'J',
          value: 5953
        }, {
          name: 'May',
          parent: 'J',
          value: 7858
        }, {
          name: 'Jun',
          parent: 'J',
          value: 6271
        }, {
          name: 'Jul',
          parent: 'J',
          value: 10887
        }, {
          name: 'Aug',
          parent: 'J',
          value: 4177
        }, {
          name: 'Sep',
          parent: 'J',
          value: 4819
        }, {
          name: 'Oct',
          parent: 'J',
          value: 6778
        }, {
          name: 'Nov',
          parent: 'J',
          value: 5176
        }, {
          name: 'Dec',
          parent: 'J',
          value: 10298
        }, {
          name: 'Jan',
          parent: 'K',
          value: 33530
        }, {
          name: 'Feb',
          parent: 'K',
          value: 17078
        }, {
          name: 'Mar',
          parent: 'K',
          value: 18169
        }, {
          name: 'Apr',
          parent: 'K',
          value: 22691
        }, {
          name: 'May',
          parent: 'K',
          value: 18402
        }, {
          name: 'Jun',
          parent: 'K',
          value: 18261
        }, {
          name: 'Jul',
          parent: 'K',
          value: 26056
        }, {
          name: 'Aug',
          parent: 'K',
          value: 27780
        }, {
          name: 'Sep',
          parent: 'K',
          value: 18993
        }, {
          name: 'Oct',
          parent: 'K',
          value: 25527
        }, {
          name: 'Nov',
          parent: 'K',
          value: 19751
        }, {
          name: 'Dec',
          parent: 'K',
          value: 24296
        }
      ]
    }
  ],
  title: {
    text: 'Besucheranzahl von 11 Mussen in 2012'
  },
  subtitle: {
    text: 'Hier wird die Proportion der Anzahl der Besucher/innen von 11 Museen gezeigt. Die Fläche von jeder Farbe repräsentiert die Anzahl der Besucher/innen von dem jeweiligen Museum, mit einem Klick auf die jeweilige Farbe können Sie noch mehr Details von jedem Monat entdecken.<br>Je größer die Fläche, desto mehr Personen haben in diesem Jahr das entsprechende Museum besucht. Sie können durch die Pfeile zwischen den Jahren 2012 bis 2016 wechseln.'
  },
  credits: {
    enabled: false
  },
  plotOptions: {
    treemap: {
      dataLabels: {
        style: {
          textOutline: false
        }
      }
    }
  },
  exporting : {
    enabled: false
  }
});
