Highcharts.chart('tree_chart_3', {
  series: [
    {
      type: "treemap",
      layoutAlgorithm: 'squarified',
      allowDrillToNode: true,
      alternateStartingDirection: true,
      levels: [
        {
          level: 1,
          layoutAlgorithm: 'squarified',
          dataLabels: {
            enabled: true,
            align: 'left',
            verticalAlign: 'top'
          }
        }
      ],
      data: [
        {
          name: 'Städtische Galerie im Lenbachhaus',
          id: 'A',
          color: '#969597'
        }, {
          name: 'Schackgalerie',
          id: 'B',
          color: '#D5AEB7'
        }, {
          name: 'Pinakothek der Moderne',
          id: 'C',
          color: '#CCCED7'
        }, {
          name: 'Neue Pinakothek',
          id: 'D',
          color: '#C7D0AE'
        }, {
          name: 'Museum Mensch und Natur',
          id: 'E',
          color: '#A5C2D4'
        }, {
          name: 'Museum Brandhorst',
          id: 'F',
          color: '#D9CFB3'
        }, {
          name: 'Münchner Stadtmuseum',
          id: 'G',
          color: '#AECCC4'
        }, {
          name: 'Deutsches Museum - Verkehrszentrum',
          id: 'H',
          colorValue: 8,
          color: '#D2BCA9'
        }, {
          name: 'Deutsches Museum - Museumsinsel',
          id: 'I',
          color: '#CB9D88'
        }, {
          name: 'Bayerisches Nationalmuseum',
          id: 'J',
          color: '#8D9C88'
        }, {
          name: 'Alte Pinakothek',
          id: 'K',
          color: '#DEEDEE'
        }, {
          name: 'Jan',
          parent: 'A',
          value: 0
        }, {
          name: 'Feb',
          parent: 'A',
          value: 33160
        }, {
          name: 'Mar',
          parent: 'A',
          value: 32570
        }, {
          name: 'Apr',
          parent: 'A',
          value: 30424
        }, {
          name: 'May',
          parent: 'A',
          value: 30643
        }, {
          name: 'Jun',
          parent: 'A',
          value: 17475
        }, {
          name: 'Jul',
          parent: 'A',
          value: 24338
        }, {
          name: 'Aug',
          parent: 'A',
          value: 30510
        }, {
          name: 'Sep',
          parent: 'A',
          value: 18940
        }, {
          name: 'Oct',
          parent: 'A',
          value: 31622
        }, {
          name: 'Nov',
          parent: 'A',
          value: 22144
        }, {
          name: 'Dec',
          parent: 'A',
          value: 21976
        }, {
          name: 'Jan',
          parent: 'B',
          value: 656
        }, {
          name: 'Feb',
          parent: 'B',
          value: 794
        }, {
          name: 'Mar',
          parent: 'B',
          value: 755
        }, {
          name: 'Apr',
          parent: 'B',
          value: 681
        }, {
          name: 'May',
          parent: 'B',
          value: 556
        }, {
          name: 'Jun',
          parent: 'B',
          value: 329
        }, {
          name: 'Jul',
          parent: 'B',
          value: 592
        }, {
          name: 'Aug',
          parent: 'B',
          value: 620
        }, {
          name: 'Sep',
          parent: 'B',
          value: 416
        }, {
          name: 'Oct',
          parent: 'B',
          value: 1579
        }, {
          name: 'Nov',
          parent: 'B',
          value: 566
        }, {
          name: 'Dec',
          parent: 'B',
          value: 340
        }, {
          name: 'Jan',
          parent: 'C',
          value: 38733
        }, {
          name: 'Feb',
          parent: 'C',
          value: 26643
        }, {
          name: 'Mar',
          parent: 'C',
          value: 23951
        }, {
          name: 'Apr',
          parent: 'C',
          value: 25408
        }, {
          name: 'May',
          parent: 'C',
          value: 23828
        }, {
          name: 'Jun',
          parent: 'C',
          value: 22993
        }, {
          name: 'Jul',
          parent: 'C',
          value: 30269
        }, {
          name: 'Aug',
          parent: 'C',
          value: 38241
        }, {
          name: 'Sep',
          parent: 'C',
          value: 19919
        }, {
          name: 'Oct',
          parent: 'C',
          value: 26417
        }, {
          name: 'Nov',
          parent: 'C',
          value: 17237
        }, {
          name: 'Dec',
          parent: 'C',
          value: 18522
        }, {
          name: 'Jan',
          parent: 'D',
          value: 15885
        }, {
          name: 'Feb',
          parent: 'D',
          value: 11405
        }, {
          name: 'Mar',
          parent: 'D',
          value: 16337
        }, {
          name: 'Apr',
          parent: 'D',
          value: 16431
        }, {
          name: 'May',
          parent: 'D',
          value: 16368
        }, {
          name: 'Jun',
          parent: 'D',
          value: 13761
        }, {
          name: 'Jul',
          parent: 'D',
          value: 17582
        }, {
          name: 'Aug',
          parent: 'D',
          value: 23040
        }, {
          name: 'Sep',
          parent: 'D',
          value: 13638
        }, {
          name: 'Oct',
          parent: 'D',
          value: 19157
        }, {
          name: 'Nov',
          parent: 'D',
          value: 15730
        }, {
          name: 'Dec',
          parent: 'D',
          value: 16133
        }, {
          name: 'Jan',
          parent: 'E',
          value: 17965
        }, {
          name: 'Feb',
          parent: 'E',
          value: 15362
        }, {
          name: 'Mar',
          parent: 'E',
          value: 15092
        }, {
          name: 'Apr',
          parent: 'E',
          value: 23155
        }, {
          name: 'May',
          parent: 'E',
          value: 18620
        }, {
          name: 'Jun',
          parent: 'E',
          value: 12237
        }, {
          name: 'Jul',
          parent: 'E',
          value: 19248
        }, {
          name: 'Aug',
          parent: 'E',
          value: 26595
        }, {
          name: 'Sep',
          parent: 'E',
          value: 13509
        }, {
          name: 'Oct',
          parent: 'E',
          value: 13879
        }, {
          name: 'Nov',
          parent: 'E',
          value: 9730
        }, {
          name: 'Dec',
          parent: 'E',
          value: 6401
        }, {
          name: 'Jan',
          parent: 'F',
          value: 10244
        }, {
          name: 'Feb',
          parent: 'F',
          value: 6917
        }, {
          name: 'Mar',
          parent: 'F',
          value: 8012
        }, {
          name: 'Apr',
          parent: 'F',
          value: 8373
        }, {
          name: 'May',
          parent: 'F',
          value: 8349
        }, {
          name: 'Jun',
          parent: 'F',
          value: 6300
        }, {
          name: 'Jul',
          parent: 'F',
          value: 10071
        }, {
          name: 'Aug',
          parent: 'F',
          value: 17950
        }, {
          name: 'Sep',
          parent: 'F',
          value: 10882
        }, {
          name: 'Oct',
          parent: 'F',
          value: 17007
        }, {
          name: 'Nov',
          parent: 'F',
          value: 12092
        }, {
          name: 'Dec',
          parent: 'F',
          value: 6204
        }, {
          name: 'Jan',
          parent: 'G',
          value: 10702
        }, {
          name: 'Feb',
          parent: 'G',
          value: 10926
        }, {
          name: 'Mar',
          parent: 'G',
          value: 15661
        }, {
          name: 'Apr',
          parent: 'G',
          value: 9624
        }, {
          name: 'May',
          parent: 'G',
          value: 11747
        }, {
          name: 'Jun',
          parent: 'G',
          value: 7190
        }, {
          name: 'Jul',
          parent: 'G',
          value: 10182
        }, {
          name: 'Aug',
          parent: 'G',
          value: 5682
        }, {
          name: 'Sep',
          parent: 'G',
          value: 9097
        }, {
          name: 'Oct',
          parent: 'G',
          value: 13846
        }, {
          name: 'Nov',
          parent: 'G',
          value: 17793
        }, {
          name: 'Dec',
          parent: 'G',
          value: 13711
        }, {
          name: 'Jan',
          parent: 'H',
          value: 11213
        }, {
          name: 'Feb',
          parent: 'H',
          value: 7354
        }, {
          name: 'Mar',
          parent: 'H',
          value: 7766
        }, {
          name: 'Apr',
          parent: 'H',
          value: 8438
        }, {
          name: 'May',
          parent: 'H',
          value: 7677
        }, {
          name: 'Jun',
          parent: 'H',
          value: 6198
        }, {
          name: 'Jul',
          parent: 'H',
          value: 9970
        }, {
          name: 'Aug',
          parent: 'H',
          value: 14909
        }, {
          name: 'Sep',
          parent: 'H',
          value: 7723
        }, {
          name: 'Oct',
          parent: 'H',
          value: 10941
        }, {
          name: 'Nov',
          parent: 'H',
          value: 8848
        }, {
          name: 'Dec',
          parent: 'H',
          value: 7254
        }, {
          name: 'Jan',
          parent: 'I',
          value: 76536
        }, {
          name: 'Feb',
          parent: 'I',
          value: 63156
        }, {
          name: 'Mar',
          parent: 'I',
          value: 86778
        }, {
          name: 'Apr',
          parent: 'I',
          value: 110863
        }, {
          name: 'May',
          parent: 'I',
          value: 85773
        }, {
          name: 'Jun',
          parent: 'I',
          value: 69844
        }, {
          name: 'Jul',
          parent: 'I',
          value: 125746
        }, {
          name: 'Aug',
          parent: 'I',
          value: 153260
        }, {
          name: 'Sep',
          parent: 'I',
          value: 73479
        }, {
          name: 'Oct',
          parent: 'I',
          value: 100320
        }, {
          name: 'Nov',
          parent: 'I',
          value: 59691
        }, {
          name: 'Dec',
          parent: 'I',
          value: 74720
        }, {
          name: 'Jan',
          parent: 'J',
          value: 6309
        }, {
          name: 'Feb',
          parent: 'J',
          value: 4278
        }, {
          name: 'Mar',
          parent: 'J',
          value: 4509
        }, {
          name: 'Apr',
          parent: 'J',
          value: 3338
        }, {
          name: 'May',
          parent: 'J',
          value: 7628
        }, {
          name: 'Jun',
          parent: 'J',
          value: 5793
        }, {
          name: 'Jul',
          parent: 'J',
          value: 8873
        }, {
          name: 'Aug',
          parent: 'J',
          value: 7594
        }, {
          name: 'Sep',
          parent: 'J',
          value: 5516
        }, {
          name: 'Oct',
          parent: 'J',
          value: 14550
        }, {
          name: 'Nov',
          parent: 'J',
          value: 10491
        }, {
          name: 'Dec',
          parent: 'J',
          value: 21728
        }, {
          name: 'Jan',
          parent: 'K',
          value: 17653
        }, {
          name: 'Feb',
          parent: 'K',
          value: 14464
        }, {
          name: 'Mar',
          parent: 'K',
          value: 16275
        }, {
          name: 'Apr',
          parent: 'K',
          value: 17310
        }, {
          name: 'May',
          parent: 'K',
          value: 17519
        }, {
          name: 'Jun',
          parent: 'K',
          value: 15161
        }, {
          name: 'Jul',
          parent: 'K',
          value: 20606
        }, {
          name: 'Aug',
          parent: 'K',
          value: 25328
        }, {
          name: 'Sep',
          parent: 'K',
          value: 14164
        }, {
          name: 'Oct',
          parent: 'K',
          value: 21913
        }, {
          name: 'Nov',
          parent: 'K',
          value: 31242
        }, {
          name: 'Dec',
          parent: 'K',
          value: 31105
        }
      ]
    }
  ],
  title: {
    text: 'Besucheranzahl von 11 Mussen in 2014'
  },
  subtitle: {
    text: 'Hier wird die Proportion der Anzahl der Besucher/innen von 11 Museen gezeigt. Die Fläche von jeder Farbe repräsentiert die Anzahl der Besucher/innen von dem jeweiligen Museum, mit einem Klick auf die jeweilige Farbe können Sie noch mehr Details von jedem Monat entdecken.<br>Je größer die Fläche, desto mehr Personen haben in diesem Jahr das entsprechende Museum besucht. Sie können durch die Pfeile zwischen den Jahren 2012 bis 2016 wechseln.'
  },
  credits: {
    enabled: false
  },
  plotOptions: {
    treemap: {
      dataLabels: {
        style: {
          textOutline: false
        }
      }
    }
  },
  exporting: {
    enabled: false
  }
});
