Highcharts.chart('tree_chart_2', {
  series: [
    {
      type: "treemap",
      layoutAlgorithm: 'squarified',
      allowDrillToNode: true,
      levelIsConstant: false,
      alternateStartingDirection: true,
      levels: [
        {
          level: 1,
          layoutAlgorithm: 'squarified',
          dataLabels: {
            enabled: true,
            align: 'left',
            verticalAlign: 'top'
          }
        }
      ],
      data: [
        {
          name: 'Städtische Galerie im Lenbachhaus',
          id: 'A',
          color: '#969597'
        }, {
          name: 'Schackgalerie',
          id: 'B',
          color: '#D5AEB7'
        }, {
          name: 'Pinakothek der Moderne',
          id: 'C',
          color: '#CCCED7'
        }, {
          name: 'Neue Pinakothek',
          id: 'D',
          color: '#C7D0AE'
        }, {
          name: 'Museum Mensch und Natur',
          id: 'E',
          color: '#A5C2D4'
        }, {
          name: 'Museum Brandhorst',
          id: 'F',
          color: '#D9CFB3'
        }, {
          name: 'Münchner Stadtmuseum',
          id: 'G',
          color: '#AECCC4'
        }, {
          name: 'Deutsches Museum - Verkehrszentrum',
          id: 'H',
          colorValue: 8,
          color: '#D2BCA9'
        }, {
          name: 'Deutsches Museum - Museumsinsel',
          id: 'I',
          color: '#CB9D88'
        }, {
          name: 'Bayerisches Nationalmuseum',
          id: 'J',
          color: '#8D9C88'
        }, {
          name: 'Alte Pinakothek',
          id: 'K',
          color: '#DEEDEE'
        }, {
          name: 'Jan',
          parent: 'A',
          value: 2973
        }, {
          name: 'Feb',
          parent: 'A',
          value: 1704
        }, {
          name: 'Mar',
          parent: 'A',
          value: 0
        }, {
          name: 'Apr',
          parent: 'A',
          value: 0
        }, {
          name: 'May',
          parent: 'A',
          value: 72835
        }, {
          name: 'Jun',
          parent: 'A',
          value: 41676
        }, {
          name: 'Jul',
          parent: 'A',
          value: 39808
        }, {
          name: 'Aug',
          parent: 'A',
          value: 41941
        }, {
          name: 'Sep',
          parent: 'A',
          value: 40164
        }, {
          name: 'Oct',
          parent: 'A',
          value: 48753
        }, {
          name: 'Nov',
          parent: 'A',
          value: 41696
        }, {
          name: 'Dec',
          parent: 'A',
          value: 41475
        }, {
          name: 'Jan',
          parent: 'B',
          value: 1012
        }, {
          name: 'Feb',
          parent: 'B',
          value: 812
        }, {
          name: 'Mar',
          parent: 'B',
          value: 1102
        }, {
          name: 'Apr',
          parent: 'B',
          value: 750
        }, {
          name: 'May',
          parent: 'B',
          value: 765
        }, {
          name: 'Jun',
          parent: 'B',
          value: 489
        }, {
          name: 'Jul',
          parent: 'B',
          value: 493
        }, {
          name: 'Aug',
          parent: 'B',
          value: 505
        }, {
          name: 'Sep',
          parent: 'B',
          value: 386
        }, {
          name: 'Oct',
          parent: 'B',
          value: 522
        }, {
          name: 'Nov',
          parent: 'B',
          value: 816
        }, {
          name: 'Dec',
          parent: 'B',
          value: 582
        }, {
          name: 'Jan',
          parent: 'C',
          value: 27926
        }, {
          name: 'Feb',
          parent: 'C',
          value: 20384
        }, {
          name: 'Mar',
          parent: 'C',
          value: 0
        }, {
          name: 'Apr',
          parent: 'C',
          value: 0
        }, {
          name: 'May',
          parent: 'C',
          value: 0
        }, {
          name: 'Jun',
          parent: 'C',
          value: 0
        }, {
          name: 'Jul',
          parent: 'C',
          value: 0
        }, {
          name: 'Aug',
          parent: 'C',
          value: 0
        }, {
          name: 'Sep',
          parent: 'C',
          value: 13792
        }, {
          name: 'Oct',
          parent: 'C',
          value: 33709
        }, {
          name: 'Nov',
          parent: 'C',
          value: 43378
        }, {
          name: 'Dec',
          parent: 'C',
          value: 31269
        }, {
          name: 'Jan',
          parent: 'D',
          value: 17788
        }, {
          name: 'Feb',
          parent: 'D',
          value: 13382
        }, {
          name: 'Mar',
          parent: 'D',
          value: 23800
        }, {
          name: 'Apr',
          parent: 'D',
          value: 23066
        }, {
          name: 'May',
          parent: 'D',
          value: 30214
        }, {
          name: 'Jun',
          parent: 'D',
          value: 19378
        }, {
          name: 'Jul',
          parent: 'D',
          value: 21137
        }, {
          name: 'Aug',
          parent: 'D',
          value: 28891
        }, {
          name: 'Sep',
          parent: 'D',
          value: 17075
        }, {
          name: 'Oct',
          parent: 'D',
          value: 15334
        }, {
          name: 'Nov',
          parent: 'D',
          value: 15303
        }, {
          name: 'Dec',
          parent: 'D',
          value: 16065
        }, {
          name: 'Jan',
          parent: 'E',
          value: 17876
        }, {
          name: 'Feb',
          parent: 'E',
          value: 21034
        }, {
          name: 'Mar',
          parent: 'E',
          value: 25800
        }, {
          name: 'Apr',
          parent: 'E',
          value: 30552
        }, {
          name: 'May',
          parent: 'E',
          value: 33810
        }, {
          name: 'Jun',
          parent: 'E',
          value: 20676
        }, {
          name: 'Jul',
          parent: 'E',
          value: 11486
        }, {
          name: 'Aug',
          parent: 'E',
          value: 11711
        }, {
          name: 'Sep',
          parent: 'E',
          value: 9911
        }, {
          name: 'Oct',
          parent: 'E',
          value: 14966
        }, {
          name: 'Nov',
          parent: 'E',
          value: 14231
        }, {
          name: 'Dec',
          parent: 'E',
          value: 8474
        }, {
          name: 'Jan',
          parent: 'F',
          value: 11251
        }, {
          name: 'Feb',
          parent: 'F',
          value: 10282
        }, {
          name: 'Mar',
          parent: 'F',
          value: 15400
        }, {
          name: 'Apr',
          parent: 'F',
          value: 10137
        }, {
          name: 'May',
          parent: 'F',
          value: 10738
        }, {
          name: 'Jun',
          parent: 'F',
          value: 6395
        }, {
          name: 'Jul',
          parent: 'F',
          value: 4977
        }, {
          name: 'Aug',
          parent: 'F',
          value: 7712
        }, {
          name: 'Sep',
          parent: 'F',
          value: 7274
        }, {
          name: 'Oct',
          parent: 'F',
          value: 9718
        }, {
          name: 'Nov',
          parent: 'F',
          value: 11108
        }, {
          name: 'Dec',
          parent: 'F',
          value: 9440
        }, {
          name: 'Jan',
          parent: 'G',
          value: 14124
        }, {
          name: 'Feb',
          parent: 'G',
          value: 16889
        }, {
          name: 'Mar',
          parent: 'G',
          value: 35036
        }, {
          name: 'Apr',
          parent: 'G',
          value: 19725
        }, {
          name: 'May',
          parent: 'G',
          value: 19218
        }, {
          name: 'Jun',
          parent: 'G',
          value: 9084
        }, {
          name: 'Jul',
          parent: 'G',
          value: 15491
        }, {
          name: 'Aug',
          parent: 'G',
          value: 8916
        }, {
          name: 'Sep',
          parent: 'G',
          value: 10256
        }, {
          name: 'Oct',
          parent: 'G',
          value: 13457
        }, {
          name: 'Nov',
          parent: 'G',
          value: 12395
        }, {
          name: 'Dec',
          parent: 'G',
          value: 9558
        }, {
          name: 'Jan',
          parent: 'H',
          value: 9330
        }, {
          name: 'Feb',
          parent: 'H',
          value: 8135
        }, {
          name: 'Mar',
          parent: 'H',
          value: 11907
        }, {
          name: 'Apr',
          parent: 'H',
          value: 11393
        }, {
          name: 'May',
          parent: 'H',
          value: 16435
        }, {
          name: 'Jun',
          parent: 'H',
          value: 8729
        }, {
          name: 'Jul',
          parent: 'H',
          value: 7234
        }, {
          name: 'Aug',
          parent: 'H',
          value: 11881
        }, {
          name: 'Sep',
          parent: 'H',
          value: 7534
        }, {
          name: 'Oct',
          parent: 'H',
          value: 9218
        }, {
          name: 'Nov',
          parent: 'H',
          value: 9459
        }, {
          name: 'Dec',
          parent: 'H',
          value: 7806
        }, {
          name: 'Jan',
          parent: 'I',
          value: 62735
        }, {
          name: 'Feb',
          parent: 'I',
          value: 61637
        }, {
          name: 'Mar',
          parent: 'I',
          value: 1115947
        }, {
          name: 'Apr',
          parent: 'I',
          value: 896583
        }, {
          name: 'May',
          parent: 'I',
          value: 1165805
        }, {
          name: 'Jun',
          parent: 'I',
          value: 70831
        }, {
          name: 'Jul',
          parent: 'I',
          value: 101634
        }, {
          name: 'Aug',
          parent: 'I',
          value: 1253821
        }, {
          name: 'Sep',
          parent: 'I',
          value: 75427
        }, {
          name: 'Oct',
          parent: 'I',
          value: 108073
        }, {
          name: 'Nov',
          parent: 'I',
          value: 79299
        }, {
          name: 'Dec',
          parent: 'I',
          value: 76640
        }, {
          name: 'Jan',
          parent: 'J',
          value: 5793
        }, {
          name: 'Feb',
          parent: 'J',
          value: 4375
        }, {
          name: 'Mar',
          parent: 'J',
          value: 4835
        }, {
          name: 'Apr',
          parent: 'J',
          value: 10094
        }, {
          name: 'May',
          parent: 'J',
          value: 20300
        }, {
          name: 'Jun',
          parent: 'J',
          value: 13913
        }, {
          name: 'Jul',
          parent: 'J',
          value: 12106
        }, {
          name: 'Aug',
          parent: 'J',
          value: 18804
        }, {
          name: 'Sep',
          parent: 'J',
          value: 11434
        }, {
          name: 'Oct',
          parent: 'J',
          value: 16190
        }, {
          name: 'Nov',
          parent: 'J',
          value: 9572
        }, {
          name: 'Dec',
          parent: 'J',
          value: 15399
        }, {
          name: 'Jan',
          parent: 'K',
          value: 18807
        }, {
          name: 'Feb',
          parent: 'K',
          value: 14828
        }, {
          name: 'Mar',
          parent: 'K',
          value: 30519
        }, {
          name: 'Apr',
          parent: 'K',
          value: 35897
        }, {
          name: 'May',
          parent: 'K',
          value: 39783
        }, {
          name: 'Jun',
          parent: 'K',
          value: 25414
        }, {
          name: 'Jul',
          parent: 'K',
          value: 18658
        }, {
          name: 'Aug',
          parent: 'K',
          value: 24708
        }, {
          name: 'Sep',
          parent: 'K',
          value: 15103
        }, {
          name: 'Oct',
          parent: 'K',
          value: 20091
        }, {
          name: 'Nov',
          parent: 'K',
          value: 16765
        }, {
          name: 'Dec',
          parent: 'K',
          value: 16911
        }
      ]
    }
  ],
  title: {
    text: 'Besucheranzahl von 11 Mussen in 2013'
  },
  subtitle: {
    text: 'Hier wird die Proportion der Anzahl der Besucher/innen von 11 Museen gezeigt. Die Fläche von jeder Farbe repräsentiert die Anzahl der Besucher/innen von dem jeweiligen Museum, mit einem Klick auf die jeweilige Farbe können Sie noch mehr Details von jedem Monat entdecken.<br>Je größer die Fläche, desto mehr Personen haben in diesem Jahr das entsprechende Museum besucht. Sie können durch die Pfeile zwischen den Jahren 2012 bis 2016 wechseln.'
  },
  credits: {
    enabled: false
  },
  plotOptions: {
    treemap: {
      dataLabels: {
        style: {
          textOutline: false
        }
      }
    }
  },
  exporting: {
    enabled: false
  }
});
